/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.menu;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComponent;


/**
 *
 * @author donatospigapiena
 */
public class MenuPause extends javax.swing.JPanel {

    /**
     * Creates new form MenuPause
     */
    public MenuPause() {
        initComponents();
        
    }
    
    public void setResume(ActionListener al){
        resumeButton.addActionListener(al);
    }
    
    public void setRestart(ActionListener al){
        restartButton.addActionListener(al);
    }
    public void setVolumeOff(ActionListener al){
        volumeOffButton.addActionListener(al);
    }
    public void setVolumeOn(ActionListener al){
        volumeOnButton.addActionListener(al);
    }
     public void setQuit(ActionListener al){
        quitButton.addActionListener(al);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quitButton = new javax.swing.JButton();
        restartButton = new javax.swing.JButton();
        resumeButton = new javax.swing.JButton();
        volumeOnButton = new javax.swing.JButton();
        volumeOffButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(406, 304));
        setMinimumSize(new java.awt.Dimension(406, 304));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        quitButton.setBackground(new java.awt.Color(0, 0, 0));
        quitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/bottoni/quit.png"))); // NOI18N
        quitButton.setBorderPainted(false);

        restartButton.setBackground(new java.awt.Color(0, 0, 0));
        restartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/bottoni/restart.png"))); // NOI18N
        restartButton.setBorderPainted(false);

        resumeButton.setBackground(new java.awt.Color(0, 0, 0));
        resumeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/bottoni/resume.png"))); // NOI18N
        resumeButton.setBorder(null);
        resumeButton.setBorderPainted(false);

        volumeOnButton.setBackground(new java.awt.Color(0, 0, 0));
        volumeOnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/bottoni/volumeon.png"))); // NOI18N
        volumeOnButton.setBorderPainted(false);

        volumeOffButton.setBackground(new java.awt.Color(0, 0, 0));
        volumeOffButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/bottoni/volumeof.png"))); // NOI18N
        volumeOffButton.setBorderPainted(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/bottoni/pausemenu_copia.png"))); // NOI18N
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(resumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(volumeOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(volumeOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(565, 565, 565))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volumeOnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volumeOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton restartButton;
    private javax.swing.JButton resumeButton;
    private javax.swing.JButton volumeOffButton;
    private javax.swing.JButton volumeOnButton;
    // End of variables declaration//GEN-END:variables
}
