/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metalscrum;


import menu.MenuGameOver;
import menu.MenuLevelTerminated;
import menu.MenuPause;
import menu.MenuStageTerminated;
import menu.MenuStart;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author stefano
 */
public class Application extends javax.swing.JFrame {

    /**
     * Creates new form Application
     */
    
    private State gameStatus;
    private Timer clock ;
    public MenuPause pause ;
    public MenuStart start;
    public MenuGameOver gameOver;
    public MenuStageTerminated stageOver;
    public MenuLevelTerminated levelOver;
    private MediaPlayer mp;
    private CollisionController cc;
    private Scene sc;
    
    public Application() {
        
        initComponents();
        
         
        setSize(GameSettings.FrameDimension.width,GameSettings.FrameDimension.height);
        setResizable(false);
        initScene();
        initCollisionController();
        //initMusic();
        //gameStatus=new StartMenuState(start);
        
    }
    
    public void run(){
        while(true){
            try {
                System.out.println("pre-gameState: "+Thread.currentThread().getName());
                Thread.sleep(5);
                gameStatus.execute();
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        System.out.println("pre-repaint: "+Thread.currentThread().getName());
                        repaint(); //To change body of generated methods, choose Tools | Templates.
                    }
                }); 
            
            } catch (InterruptedException ex) {
                Logger.getLogger(Application.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
   
    
   
    
   
    
    
    @Override
    public void setVisible(boolean isVisible){
        super.setVisible(isVisible);
        
    }
    
    
    private void initScene(){
        sc = Scene.getInstance();
        getContentPane().add(sc);
        sc.setSize(GameSettings.FrameDimension.width,GameSettings.FrameDimension.width);
        sc.setVisible(false);
        
    }
    
    private void initCollisionController(){
        cc = CollisionController.getInstance();
    }
    
    private void initMusic() {
         new JFXPanel();
        String path=("src/resources/music.mp3");
        
        Media hit = new Media(new File(path).toURI().toString());
        mp = new MediaPlayer(hit);
        mp.play();
    }
    
    public  State getStatus(){
        return gameStatus;
    }
    
    public  void setStatus(State newState){
        gameStatus = newState;
    } 
    
    public Player getCurrentPlayer(){
        return gameStatus.getPlayer();
    }
    
    public GameLevel getCurrentGameLevel(){
        return gameStatus.getGameLevel();
    }
    
    public List<CharacterController> getCurrentControllers(){
        return gameStatus.getControllers();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
   
            
       
            
       
    
   
    
    
    
    
    
    private class VolumeOffListener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            mp.pause();
        }

}
    
    private class VolumeOnListener implements ActionListener{
        
        @Override
        public void actionPerformed(ActionEvent e) {
            mp.play();
        }

}
}

    
   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables



